CREATE TABLE UserRoles (
  ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  UserID char(32) NOT NULL,
  AppID varchar(32),
  OrganizationId varchar(32),
  RoleName varchar(32),
  RoleValues varchar(256)
);

CREATE TABLE Applications (
  ID varchar(32),
  Name varchar(128),
  DefaultRole varchar(30) default null,
  DefaultOrgid varchar(30) default null
);

CREATE TABLE Organization (
  ID varchar(32),
  Name varchar(128)
);

CREATE TABLE Roles (
  ID varchar(32),
  Name varchar(128)
);

